
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action articuloRefreshAction;
	private global::Gtk.Action articuloAddAction;
	private global::Gtk.Action articuloDeleteAction;
	private global::Gtk.Action articuloEditAction;
	private global::Gtk.Action categoriaRefreshAction;
	private global::Gtk.Action categoriaAddAction;
	private global::Gtk.Action categoriaDeleteAction;
	private global::Gtk.Action categoriaEditAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.Notebook notebook1;
	private global::PArticulo.ListArticuloView listarticuloview1;
	private global::Gtk.Label label1;
	private global::PArticulo.ListCategoriaView listcategoriaview1;
	private global::Gtk.Label label2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.articuloRefreshAction = new global::Gtk.Action ("articuloRefreshAction", null, null, "gtk-refresh");
		w1.Add (this.articuloRefreshAction, null);
		this.articuloAddAction = new global::Gtk.Action ("articuloAddAction", null, null, "gtk-add");
		w1.Add (this.articuloAddAction, null);
		this.articuloDeleteAction = new global::Gtk.Action ("articuloDeleteAction", null, null, "gtk-delete");
		w1.Add (this.articuloDeleteAction, null);
		this.articuloEditAction = new global::Gtk.Action ("articuloEditAction", null, null, "gtk-edit");
		w1.Add (this.articuloEditAction, null);
		this.categoriaRefreshAction = new global::Gtk.Action ("categoriaRefreshAction", null, null, "gtk-refresh");
		w1.Add (this.categoriaRefreshAction, null);
		this.categoriaAddAction = new global::Gtk.Action ("categoriaAddAction", null, null, "gtk-add");
		w1.Add (this.categoriaAddAction, null);
		this.categoriaDeleteAction = new global::Gtk.Action ("categoriaDeleteAction", null, null, "gtk-delete");
		w1.Add (this.categoriaDeleteAction, null);
		this.categoriaEditAction = new global::Gtk.Action ("categoriaEditAction", null, null, "gtk-edit");
		w1.Add (this.categoriaEditAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.listarticuloview1 = new global::PArticulo.ListArticuloView ();
		this.listarticuloview1.Events = ((global::Gdk.EventMask)(256));
		this.listarticuloview1.Name = "listarticuloview1";
		this.notebook1.Add (this.listarticuloview1);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Artículo");
		this.notebook1.SetTabLabel (this.listarticuloview1, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.listcategoriaview1 = new global::PArticulo.ListCategoriaView ();
		this.listcategoriaview1.Events = ((global::Gdk.EventMask)(256));
		this.listcategoriaview1.Name = "listcategoriaview1";
		this.notebook1.Add (this.listcategoriaview1);
		global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.listcategoriaview1]));
		w3.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Categoría");
		this.notebook1.SetTabLabel (this.listcategoriaview1, this.label2);
		this.label2.ShowAll ();
		this.vbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
		w4.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
