
// This file has been generated by the GUI designer. Do not modify.
namespace PArticulo
{
	public partial class ArticuloFindView
	{
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label1;
		private global::Gtk.Entry entryIdArticulo;
		private global::Gtk.Button buttonListarId;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label label2;
		private global::Gtk.Entry entryNombreArticulo;
		private global::Gtk.Button buttonListarNombre;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeviewBuscarArticulo;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label GtkLabel1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PArticulo.ArticuloFindView
			this.Name = "PArticulo.ArticuloFindView";
			this.Title = global::Mono.Unix.Catalog.GetString ("ArticuloFindView");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child PArticulo.ArticuloFindView.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Por id:");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entryIdArticulo = new global::Gtk.Entry ();
			this.entryIdArticulo.CanFocus = true;
			this.entryIdArticulo.Name = "entryIdArticulo";
			this.entryIdArticulo.IsEditable = true;
			this.entryIdArticulo.InvisibleChar = '•';
			this.hbox2.Add (this.entryIdArticulo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entryIdArticulo]));
			w2.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonListarId = new global::Gtk.Button ();
			this.buttonListarId.CanFocus = true;
			this.buttonListarId.Name = "buttonListarId";
			this.buttonListarId.UseUnderline = true;
			this.buttonListarId.Label = global::Mono.Unix.Catalog.GetString ("Listar");
			this.hbox2.Add (this.buttonListarId);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonListarId]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Por nombre:");
			this.hbox4.Add (this.label2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entryNombreArticulo = new global::Gtk.Entry ();
			this.entryNombreArticulo.CanFocus = true;
			this.entryNombreArticulo.Name = "entryNombreArticulo";
			this.entryNombreArticulo.IsEditable = true;
			this.entryNombreArticulo.InvisibleChar = '•';
			this.hbox4.Add (this.entryNombreArticulo);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entryNombreArticulo]));
			w6.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonListarNombre = new global::Gtk.Button ();
			this.buttonListarNombre.CanFocus = true;
			this.buttonListarNombre.Name = "buttonListarNombre";
			this.buttonListarNombre.UseUnderline = true;
			this.buttonListarNombre.Label = global::Mono.Unix.Catalog.GetString ("Listar");
			this.hbox4.Add (this.buttonListarNombre);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.buttonListarNombre]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeviewBuscarArticulo = new global::Gtk.TreeView ();
			this.treeviewBuscarArticulo.CanFocus = true;
			this.treeviewBuscarArticulo.Name = "treeviewBuscarArticulo";
			this.GtkScrolledWindow.Add (this.treeviewBuscarArticulo);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w10.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w11.Position = 3;
			this.GtkAlignment.Add (this.vbox1);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Buscar artículo</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel1;
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.buttonListarId.Clicked += new global::System.EventHandler (this.OnButtonListarIdClicked);
			this.buttonListarNombre.Activated += new global::System.EventHandler (this.OnButtonListarNombreActivated);
		}
	}
}
